// Code generated by protoc-gen-go.
// source: query.proto
// DO NOT EDIT!

/*
Package query is a generated protocol buffer package.

It is generated from these files:
	query.proto

It has these top-level messages:
	Target
	VTGateCallerID
	EventToken
	Value
	BindVariable
	BoundQuery
	ExecuteOptions
	Field
	Row
	ResultExtras
	QueryResult
	StreamEvent
	ExecuteRequest
	ExecuteResponse
	ResultWithError
	ExecuteBatchRequest
	ExecuteBatchResponse
	StreamExecuteRequest
	StreamExecuteResponse
	BeginRequest
	BeginResponse
	CommitRequest
	CommitResponse
	RollbackRequest
	RollbackResponse
	PrepareRequest
	PrepareResponse
	CommitPreparedRequest
	CommitPreparedResponse
	RollbackPreparedRequest
	RollbackPreparedResponse
	CreateTransactionRequest
	CreateTransactionResponse
	StartCommitRequest
	StartCommitResponse
	SetRollbackRequest
	SetRollbackResponse
	ConcludeTransactionRequest
	ConcludeTransactionResponse
	ReadTransactionRequest
	ReadTransactionResponse
	BeginExecuteRequest
	BeginExecuteResponse
	BeginExecuteBatchRequest
	BeginExecuteBatchResponse
	SplitQueryRequest
	QuerySplit
	SplitQueryResponse
	StreamHealthRequest
	RealtimeStats
	StreamHealthResponse
	UpdateStreamRequest
	UpdateStreamResponse
	TransactionMetadata
*/
package query

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import topodata "github.com/youtube/vitess/go/vt/proto/topodata"
import vtrpc "github.com/youtube/vitess/go/vt/proto/vtrpc"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Flags sent from the MySQL C API
type MySqlFlag int32

const (
	MySqlFlag_EMPTY                 MySqlFlag = 0
	MySqlFlag_NOT_NULL_FLAG         MySqlFlag = 1
	MySqlFlag_PRI_KEY_FLAG          MySqlFlag = 2
	MySqlFlag_UNIQUE_KEY_FLAG       MySqlFlag = 4
	MySqlFlag_MULTIPLE_KEY_FLAG     MySqlFlag = 8
	MySqlFlag_BLOB_FLAG             MySqlFlag = 16
	MySqlFlag_UNSIGNED_FLAG         MySqlFlag = 32
	MySqlFlag_ZEROFILL_FLAG         MySqlFlag = 64
	MySqlFlag_BINARY_FLAG           MySqlFlag = 128
	MySqlFlag_ENUM_FLAG             MySqlFlag = 256
	MySqlFlag_AUTO_INCREMENT_FLAG   MySqlFlag = 512
	MySqlFlag_TIMESTAMP_FLAG        MySqlFlag = 1024
	MySqlFlag_SET_FLAG              MySqlFlag = 2048
	MySqlFlag_NO_DEFAULT_VALUE_FLAG MySqlFlag = 4096
	MySqlFlag_ON_UPDATE_NOW_FLAG    MySqlFlag = 8192
	MySqlFlag_NUM_FLAG              MySqlFlag = 32768
	MySqlFlag_PART_KEY_FLAG         MySqlFlag = 16384
	MySqlFlag_GROUP_FLAG            MySqlFlag = 32768
	MySqlFlag_UNIQUE_FLAG           MySqlFlag = 65536
	MySqlFlag_BINCMP_FLAG           MySqlFlag = 131072
)

var MySqlFlag_name = map[int32]string{
	0:     "EMPTY",
	1:     "NOT_NULL_FLAG",
	2:     "PRI_KEY_FLAG",
	4:     "UNIQUE_KEY_FLAG",
	8:     "MULTIPLE_KEY_FLAG",
	16:    "BLOB_FLAG",
	32:    "UNSIGNED_FLAG",
	64:    "ZEROFILL_FLAG",
	128:   "BINARY_FLAG",
	256:   "ENUM_FLAG",
	512:   "AUTO_INCREMENT_FLAG",
	1024:  "TIMESTAMP_FLAG",
	2048:  "SET_FLAG",
	4096:  "NO_DEFAULT_VALUE_FLAG",
	8192:  "ON_UPDATE_NOW_FLAG",
	32768: "NUM_FLAG",
	16384: "PART_KEY_FLAG",
	// Duplicate value: 32768: "GROUP_FLAG",
	65536:  "UNIQUE_FLAG",
	131072: "BINCMP_FLAG",
}
var MySqlFlag_value = map[string]int32{
	"EMPTY":                 0,
	"NOT_NULL_FLAG":         1,
	"PRI_KEY_FLAG":          2,
	"UNIQUE_KEY_FLAG":       4,
	"MULTIPLE_KEY_FLAG":     8,
	"BLOB_FLAG":             16,
	"UNSIGNED_FLAG":         32,
	"ZEROFILL_FLAG":         64,
	"BINARY_FLAG":           128,
	"ENUM_FLAG":             256,
	"AUTO_INCREMENT_FLAG":   512,
	"TIMESTAMP_FLAG":        1024,
	"SET_FLAG":              2048,
	"NO_DEFAULT_VALUE_FLAG": 4096,
	"ON_UPDATE_NOW_FLAG":    8192,
	"NUM_FLAG":              32768,
	"PART_KEY_FLAG":         16384,
	"GROUP_FLAG":            32768,
	"UNIQUE_FLAG":           65536,
	"BINCMP_FLAG":           131072,
}

func (x MySqlFlag) String() string {
	return proto.EnumName(MySqlFlag_name, int32(x))
}
func (MySqlFlag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Flag allows us to qualify types by their common properties.
type Flag int32

const (
	Flag_NONE       Flag = 0
	Flag_ISINTEGRAL Flag = 256
	Flag_ISUNSIGNED Flag = 512
	Flag_ISFLOAT    Flag = 1024
	Flag_ISQUOTED   Flag = 2048
	Flag_ISTEXT     Flag = 4096
	Flag_ISBINARY   Flag = 8192
)

var Flag_name = map[int32]string{
	0:    "NONE",
	256:  "ISINTEGRAL",
	512:  "ISUNSIGNED",
	1024: "ISFLOAT",
	2048: "ISQUOTED",
	4096: "ISTEXT",
	8192: "ISBINARY",
}
var Flag_value = map[string]int32{
	"NONE":       0,
	"ISINTEGRAL": 256,
	"ISUNSIGNED": 512,
	"ISFLOAT":    1024,
	"ISQUOTED":   2048,
	"ISTEXT":     4096,
	"ISBINARY":   8192,
}

func (x Flag) String() string {
	return proto.EnumName(Flag_name, int32(x))
}
func (Flag) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// Type defines the various supported data types in bind vars
// and query results.
type Type int32

const (
	// NULL_TYPE specifies a NULL type.
	Type_NULL_TYPE Type = 0
	// INT8 specifies a TINYINT type.
	// Properties: 1, IsNumber.
	Type_INT8 Type = 257
	// UINT8 specifies a TINYINT UNSIGNED type.
	// Properties: 2, IsNumber, IsUnsigned.
	Type_UINT8 Type = 770
	// INT16 specifies a SMALLINT type.
	// Properties: 3, IsNumber.
	Type_INT16 Type = 259
	// UINT16 specifies a SMALLINT UNSIGNED type.
	// Properties: 4, IsNumber, IsUnsigned.
	Type_UINT16 Type = 772
	// INT24 specifies a MEDIUMINT type.
	// Properties: 5, IsNumber.
	Type_INT24 Type = 261
	// UINT24 specifies a MEDIUMINT UNSIGNED type.
	// Properties: 6, IsNumber, IsUnsigned.
	Type_UINT24 Type = 774
	// INT32 specifies a INTEGER type.
	// Properties: 7, IsNumber.
	Type_INT32 Type = 263
	// UINT32 specifies a INTEGER UNSIGNED type.
	// Properties: 8, IsNumber, IsUnsigned.
	Type_UINT32 Type = 776
	// INT64 specifies a BIGINT type.
	// Properties: 9, IsNumber.
	Type_INT64 Type = 265
	// UINT64 specifies a BIGINT UNSIGNED type.
	// Properties: 10, IsNumber, IsUnsigned.
	Type_UINT64 Type = 778
	// FLOAT32 specifies a FLOAT type.
	// Properties: 11, IsFloat.
	Type_FLOAT32 Type = 1035
	// FLOAT64 specifies a DOUBLE or REAL type.
	// Properties: 12, IsFloat.
	Type_FLOAT64 Type = 1036
	// TIMESTAMP specifies a TIMESTAMP type.
	// Properties: 13, IsQuoted.
	Type_TIMESTAMP Type = 2061
	// DATE specifies a DATE type.
	// Properties: 14, IsQuoted.
	Type_DATE Type = 2062
	// TIME specifies a TIME type.
	// Properties: 15, IsQuoted.
	Type_TIME Type = 2063
	// DATETIME specifies a DATETIME type.
	// Properties: 16, IsQuoted.
	Type_DATETIME Type = 2064
	// YEAR specifies a YEAR type.
	// Properties: 17, IsNumber, IsUnsigned.
	Type_YEAR Type = 785
	// DECIMAL specifies a DECIMAL or NUMERIC type.
	// Properties: 18, None.
	Type_DECIMAL Type = 18
	// TEXT specifies a TEXT type.
	// Properties: 19, IsQuoted, IsText.
	Type_TEXT Type = 6163
	// BLOB specifies a BLOB type.
	// Properties: 20, IsQuoted, IsBinary.
	Type_BLOB Type = 10260
	// VARCHAR specifies a VARCHAR type.
	// Properties: 21, IsQuoted, IsText.
	Type_VARCHAR Type = 6165
	// VARBINARY specifies a VARBINARY type.
	// Properties: 22, IsQuoted, IsBinary.
	Type_VARBINARY Type = 10262
	// CHAR specifies a CHAR type.
	// Properties: 23, IsQuoted, IsText.
	Type_CHAR Type = 6167
	// BINARY specifies a BINARY type.
	// Properties: 24, IsQuoted, IsBinary.
	Type_BINARY Type = 10264
	// BIT specifies a BIT type.
	// Properties: 25, IsQuoted.
	Type_BIT Type = 2073
	// ENUM specifies an ENUM type.
	// Properties: 26, IsQuoted.
	Type_ENUM Type = 2074
	// SET specifies a SET type.
	// Properties: 27, IsQuoted.
	Type_SET Type = 2075
	// TUPLE specifies a a tuple. This cannot
	// be returned in a QueryResult, but it can
	// be sent as a bind var.
	// Properties: 28, None.
	Type_TUPLE Type = 28
	// GEOMETRY specifies a GEOMETRY type.
	// Properties: 29, IsQuoted.
	Type_GEOMETRY Type = 2077
	// JSON specified a JSON type.
	// Properties: 30, IsQuoted.
	Type_JSON Type = 2078
)

var Type_name = map[int32]string{
	0:     "NULL_TYPE",
	257:   "INT8",
	770:   "UINT8",
	259:   "INT16",
	772:   "UINT16",
	261:   "INT24",
	774:   "UINT24",
	263:   "INT32",
	776:   "UINT32",
	265:   "INT64",
	778:   "UINT64",
	1035:  "FLOAT32",
	1036:  "FLOAT64",
	2061:  "TIMESTAMP",
	2062:  "DATE",
	2063:  "TIME",
	2064:  "DATETIME",
	785:   "YEAR",
	18:    "DECIMAL",
	6163:  "TEXT",
	10260: "BLOB",
	6165:  "VARCHAR",
	10262: "VARBINARY",
	6167:  "CHAR",
	10264: "BINARY",
	2073:  "BIT",
	2074:  "ENUM",
	2075:  "SET",
	28:    "TUPLE",
	2077:  "GEOMETRY",
	2078:  "JSON",
}
var Type_value = map[string]int32{
	"NULL_TYPE": 0,
	"INT8":      257,
	"UINT8":     770,
	"INT16":     259,
	"UINT16":    772,
	"INT24":     261,
	"UINT24":    774,
	"INT32":     263,
	"UINT32":    776,
	"INT64":     265,
	"UINT64":    778,
	"FLOAT32":   1035,
	"FLOAT64":   1036,
	"TIMESTAMP": 2061,
	"DATE":      2062,
	"TIME":      2063,
	"DATETIME":  2064,
	"YEAR":      785,
	"DECIMAL":   18,
	"TEXT":      6163,
	"BLOB":      10260,
	"VARCHAR":   6165,
	"VARBINARY": 10262,
	"CHAR":      6167,
	"BINARY":    10264,
	"BIT":       2073,
	"ENUM":      2074,
	"SET":       2075,
	"TUPLE":     28,
	"GEOMETRY":  2077,
	"JSON":      2078,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// TransactionState represents the state of a distributed transaction.
type TransactionState int32

const (
	TransactionState_UNKNOWN  TransactionState = 0
	TransactionState_PREPARE  TransactionState = 1
	TransactionState_COMMIT   TransactionState = 2
	TransactionState_ROLLBACK TransactionState = 3
)

var TransactionState_name = map[int32]string{
	0: "UNKNOWN",
	1: "PREPARE",
	2: "COMMIT",
	3: "ROLLBACK",
}
var TransactionState_value = map[string]int32{
	"UNKNOWN":  0,
	"PREPARE":  1,
	"COMMIT":   2,
	"ROLLBACK": 3,
}

func (x TransactionState) String() string {
	return proto.EnumName(TransactionState_name, int32(x))
}
func (TransactionState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// The category of one statement.
type StreamEvent_Statement_Category int32

const (
	StreamEvent_Statement_Error StreamEvent_Statement_Category = 0
	StreamEvent_Statement_DML   StreamEvent_Statement_Category = 1
	StreamEvent_Statement_DDL   StreamEvent_Statement_Category = 2
)

var StreamEvent_Statement_Category_name = map[int32]string{
	0: "Error",
	1: "DML",
	2: "DDL",
}
var StreamEvent_Statement_Category_value = map[string]int32{
	"Error": 0,
	"DML":   1,
	"DDL":   2,
}

func (x StreamEvent_Statement_Category) String() string {
	return proto.EnumName(StreamEvent_Statement_Category_name, int32(x))
}
func (StreamEvent_Statement_Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0, 0}
}

type SplitQueryRequest_Algorithm int32

const (
	SplitQueryRequest_EQUAL_SPLITS SplitQueryRequest_Algorithm = 0
	SplitQueryRequest_FULL_SCAN    SplitQueryRequest_Algorithm = 1
)

var SplitQueryRequest_Algorithm_name = map[int32]string{
	0: "EQUAL_SPLITS",
	1: "FULL_SCAN",
}
var SplitQueryRequest_Algorithm_value = map[string]int32{
	"EQUAL_SPLITS": 0,
	"FULL_SCAN":    1,
}

func (x SplitQueryRequest_Algorithm) String() string {
	return proto.EnumName(SplitQueryRequest_Algorithm_name, int32(x))
}
func (SplitQueryRequest_Algorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{45, 0}
}

// Target describes what the client expects the tablet is.
// If the tablet does not match, an error is returned.
type Target struct {
	Keyspace   string              `protobuf:"bytes,1,opt,name=keyspace" json:"keyspace,omitempty"`
	Shard      string              `protobuf:"bytes,2,opt,name=shard" json:"shard,omitempty"`
	TabletType topodata.TabletType `protobuf:"varint,3,opt,name=tablet_type,json=tabletType,enum=topodata.TabletType" json:"tablet_type,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// VTGateCallerID is sent by VTGate to VTTablet to describe the
// caller. If possible, this information is secure. For instance,
// if using unique certificates that guarantee that VTGate->VTTablet
// traffic cannot be spoofed, then VTTablet can trust this information,
// and VTTablet will use it for tablet ACLs, for instance.
// Because of this security guarantee, this is different than the CallerID
// structure, which is not secure at all, because it is provided
// by the Vitess client.
type VTGateCallerID struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *VTGateCallerID) Reset()                    { *m = VTGateCallerID{} }
func (m *VTGateCallerID) String() string            { return proto.CompactTextString(m) }
func (*VTGateCallerID) ProtoMessage()               {}
func (*VTGateCallerID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// EventToken is a structure that describes a point in time in a
// replication stream on one shard. The most recent known replication
// position can be retrieved from vttablet when executing a query. It
// is also sent with the replication streams from the binlog service.
type EventToken struct {
	// timestamp is the MySQL timestamp of the statements. Seconds since Epoch.
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	// The shard name that applied the statements. Note this is not set when
	// streaming from a vttablet. It is only used on the client -> vtgate link.
	Shard string `protobuf:"bytes,2,opt,name=shard" json:"shard,omitempty"`
	// The position on the replication stream after this statement was applied.
	// It is not the transaction ID / GTID, but the position / GTIDSet.
	Position string `protobuf:"bytes,3,opt,name=position" json:"position,omitempty"`
}

func (m *EventToken) Reset()                    { *m = EventToken{} }
func (m *EventToken) String() string            { return proto.CompactTextString(m) }
func (*EventToken) ProtoMessage()               {}
func (*EventToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// Value represents a typed value.
type Value struct {
	Type  Type   `protobuf:"varint,1,opt,name=type,enum=query.Type" json:"type,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// BindVariable represents a single bind variable in a Query.
type BindVariable struct {
	Type  Type   `protobuf:"varint,1,opt,name=type,enum=query.Type" json:"type,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// values are set if type is TUPLE.
	Values []*Value `protobuf:"bytes,3,rep,name=values" json:"values,omitempty"`
}

func (m *BindVariable) Reset()                    { *m = BindVariable{} }
func (m *BindVariable) String() string            { return proto.CompactTextString(m) }
func (*BindVariable) ProtoMessage()               {}
func (*BindVariable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BindVariable) GetValues() []*Value {
	if m != nil {
		return m.Values
	}
	return nil
}

// BoundQuery is a query with its bind variables
type BoundQuery struct {
	// sql is the SQL query to execute
	Sql string `protobuf:"bytes,1,opt,name=sql" json:"sql,omitempty"`
	// bind_variables is a map of all bind variables to expand in the query
	BindVariables map[string]*BindVariable `protobuf:"bytes,2,rep,name=bind_variables,json=bindVariables" json:"bind_variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *BoundQuery) Reset()                    { *m = BoundQuery{} }
func (m *BoundQuery) String() string            { return proto.CompactTextString(m) }
func (*BoundQuery) ProtoMessage()               {}
func (*BoundQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *BoundQuery) GetBindVariables() map[string]*BindVariable {
	if m != nil {
		return m.BindVariables
	}
	return nil
}

// ExecuteOptions is passed around for all Execute calls.
type ExecuteOptions struct {
	// Deprecated, see exclude_field_metadata instead
	ExcludeFieldNames bool `protobuf:"varint,1,opt,name=exclude_field_names,json=excludeFieldNames" json:"exclude_field_names,omitempty"`
	// If set, we will try to include an EventToken with the responses.
	IncludeEventToken bool `protobuf:"varint,2,opt,name=include_event_token,json=includeEventToken" json:"include_event_token,omitempty"`
	// If set, the fresher field may be set as a result comparison to this token.
	// This is a shortcut so the application doesn't need to care about
	// comparing EventTokens.
	CompareEventToken *EventToken `protobuf:"bytes,3,opt,name=compare_event_token,json=compareEventToken" json:"compare_event_token,omitempty"`
	// If set, the resulting Field array won't have metadata such as
	// field name, table name, etc. This is an optimization for high-QPS queries where
	// the client knows what it's getting
	ExcludeFieldMetadata bool `protobuf:"varint,4,opt,name=exclude_field_metadata,json=excludeFieldMetadata" json:"exclude_field_metadata,omitempty"`
}

func (m *ExecuteOptions) Reset()                    { *m = ExecuteOptions{} }
func (m *ExecuteOptions) String() string            { return proto.CompactTextString(m) }
func (*ExecuteOptions) ProtoMessage()               {}
func (*ExecuteOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ExecuteOptions) GetCompareEventToken() *EventToken {
	if m != nil {
		return m.CompareEventToken
	}
	return nil
}

// Field describes a single column returned by a query
type Field struct {
	// name of the field as returned by mysql C API
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// vitess-defined type. Conversion function is in sqltypes package.
	Type         Type   `protobuf:"varint,2,opt,name=type,enum=query.Type" json:"type,omitempty"`
	Table        string `protobuf:"bytes,3,opt,name=table" json:"table,omitempty"`
	OrgTable     string `protobuf:"bytes,4,opt,name=org_table,json=orgTable" json:"org_table,omitempty"`
	Database     string `protobuf:"bytes,5,opt,name=database" json:"database,omitempty"`
	OrgName      string `protobuf:"bytes,6,opt,name=org_name,json=orgName" json:"org_name,omitempty"`
	ColumnLength uint64 `protobuf:"varint,7,opt,name=column_length,json=columnLength" json:"column_length,omitempty"`
	Charset      uint32 `protobuf:"varint,8,opt,name=charset" json:"charset,omitempty"`
	Decimals     uint32 `protobuf:"varint,9,opt,name=decimals" json:"decimals,omitempty"`
	Flags        uint32 `protobuf:"varint,10,opt,name=flags" json:"flags,omitempty"`
}

func (m *Field) Reset()                    { *m = Field{} }
func (m *Field) String() string            { return proto.CompactTextString(m) }
func (*Field) ProtoMessage()               {}
func (*Field) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

// Row is a database row.
type Row struct {
	// lengths contains the length of each value in values.
	// A length of -1 means that the field is NULL. While
	// reading values, you have to accummulate the length
	// to know the offset where the next value begins in values.
	Lengths []int64 `protobuf:"zigzag64,1,rep,packed,name=lengths" json:"lengths,omitempty"`
	// values contains a concatenation of all values in the row.
	Values []byte `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

// ResultExtras contains optional out-of-band information. Usually the
// extras are requested by adding ExecuteOptions flags.
type ResultExtras struct {
	// event_token is populated if the include_event_token flag is set
	// in ExecuteOptions.
	EventToken *EventToken `protobuf:"bytes,1,opt,name=event_token,json=eventToken" json:"event_token,omitempty"`
	// If set, it means the data returned with this result is fresher
	// than the compare_token passed in the ExecuteOptions.
	Fresher bool `protobuf:"varint,2,opt,name=fresher" json:"fresher,omitempty"`
}

func (m *ResultExtras) Reset()                    { *m = ResultExtras{} }
func (m *ResultExtras) String() string            { return proto.CompactTextString(m) }
func (*ResultExtras) ProtoMessage()               {}
func (*ResultExtras) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ResultExtras) GetEventToken() *EventToken {
	if m != nil {
		return m.EventToken
	}
	return nil
}

// QueryResult is returned by Execute and ExecuteStream.
//
// As returned by Execute, len(fields) is always equal to len(row)
// (for each row in rows).
//
// As returned by StreamExecute, the first QueryResult has the fields
// set, and subsequent QueryResult have rows set. And as Execute,
// len(QueryResult[0].fields) is always equal to len(row) (for each
// row in rows for each QueryResult in QueryResult[1:]).
type QueryResult struct {
	Fields       []*Field      `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty"`
	RowsAffected uint64        `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected" json:"rows_affected,omitempty"`
	InsertId     uint64        `protobuf:"varint,3,opt,name=insert_id,json=insertId" json:"insert_id,omitempty"`
	Rows         []*Row        `protobuf:"bytes,4,rep,name=rows" json:"rows,omitempty"`
	Extras       *ResultExtras `protobuf:"bytes,5,opt,name=extras" json:"extras,omitempty"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *QueryResult) GetFields() []*Field {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *QueryResult) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

func (m *QueryResult) GetExtras() *ResultExtras {
	if m != nil {
		return m.Extras
	}
	return nil
}

// StreamEvent describes a set of transformations that happened as a
// single transactional unit on a server. It is streamed back by the
// Update Stream calls.
type StreamEvent struct {
	// The statements in this transaction.
	Statements []*StreamEvent_Statement `protobuf:"bytes,1,rep,name=statements" json:"statements,omitempty"`
	// The Event Token for this event.
	EventToken *EventToken `protobuf:"bytes,2,opt,name=event_token,json=eventToken" json:"event_token,omitempty"`
}

func (m *StreamEvent) Reset()                    { *m = StreamEvent{} }
func (m *StreamEvent) String() string            { return proto.CompactTextString(m) }
func (*StreamEvent) ProtoMessage()               {}
func (*StreamEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *StreamEvent) GetStatements() []*StreamEvent_Statement {
	if m != nil {
		return m.Statements
	}
	return nil
}

func (m *StreamEvent) GetEventToken() *EventToken {
	if m != nil {
		return m.EventToken
	}
	return nil
}

// One individual Statement in a transaction.
type StreamEvent_Statement struct {
	Category StreamEvent_Statement_Category `protobuf:"varint,1,opt,name=category,enum=query.StreamEvent_Statement_Category" json:"category,omitempty"`
	// table_name, primary_key_fields and primary_key_values are set for DML.
	TableName        string   `protobuf:"bytes,2,opt,name=table_name,json=tableName" json:"table_name,omitempty"`
	PrimaryKeyFields []*Field `protobuf:"bytes,3,rep,name=primary_key_fields,json=primaryKeyFields" json:"primary_key_fields,omitempty"`
	PrimaryKeyValues []*Row   `protobuf:"bytes,4,rep,name=primary_key_values,json=primaryKeyValues" json:"primary_key_values,omitempty"`
	// sql is set for all queries.
	// FIXME(alainjobart) we may not need it for DMLs.
	Sql []byte `protobuf:"bytes,5,opt,name=sql,proto3" json:"sql,omitempty"`
}

func (m *StreamEvent_Statement) Reset()                    { *m = StreamEvent_Statement{} }
func (m *StreamEvent_Statement) String() string            { return proto.CompactTextString(m) }
func (*StreamEvent_Statement) ProtoMessage()               {}
func (*StreamEvent_Statement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11, 0} }

func (m *StreamEvent_Statement) GetPrimaryKeyFields() []*Field {
	if m != nil {
		return m.PrimaryKeyFields
	}
	return nil
}

func (m *StreamEvent_Statement) GetPrimaryKeyValues() []*Row {
	if m != nil {
		return m.PrimaryKeyValues
	}
	return nil
}

// ExecuteRequest is the payload to Execute
type ExecuteRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Query             *BoundQuery     `protobuf:"bytes,4,opt,name=query" json:"query,omitempty"`
	TransactionId     int64           `protobuf:"varint,5,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	Options           *ExecuteOptions `protobuf:"bytes,6,opt,name=options" json:"options,omitempty"`
}

func (m *ExecuteRequest) Reset()                    { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()               {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ExecuteRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *ExecuteRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *ExecuteRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *ExecuteRequest) GetQuery() *BoundQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *ExecuteRequest) GetOptions() *ExecuteOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// ExecuteResponse is the returned value from Execute
type ExecuteResponse struct {
	Result *QueryResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ExecuteResponse) Reset()                    { *m = ExecuteResponse{} }
func (m *ExecuteResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteResponse) ProtoMessage()               {}
func (*ExecuteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ExecuteResponse) GetResult() *QueryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// ResultWithError represents a query response
// in the form of result or error but not both.
// TODO: To be used in ExecuteBatchResponse and BeginExecuteBatchResponse.
type ResultWithError struct {
	// error contains an query level error, only set if result is unset.
	Error *vtrpc.RPCError `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	// result contains the query result, only set if error is unset.
	Result *QueryResult `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *ResultWithError) Reset()                    { *m = ResultWithError{} }
func (m *ResultWithError) String() string            { return proto.CompactTextString(m) }
func (*ResultWithError) ProtoMessage()               {}
func (*ResultWithError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ResultWithError) GetError() *vtrpc.RPCError {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *ResultWithError) GetResult() *QueryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// ExecuteBatchRequest is the payload to ExecuteBatch
type ExecuteBatchRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Queries           []*BoundQuery   `protobuf:"bytes,4,rep,name=queries" json:"queries,omitempty"`
	AsTransaction     bool            `protobuf:"varint,5,opt,name=as_transaction,json=asTransaction" json:"as_transaction,omitempty"`
	TransactionId     int64           `protobuf:"varint,6,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	Options           *ExecuteOptions `protobuf:"bytes,7,opt,name=options" json:"options,omitempty"`
}

func (m *ExecuteBatchRequest) Reset()                    { *m = ExecuteBatchRequest{} }
func (m *ExecuteBatchRequest) String() string            { return proto.CompactTextString(m) }
func (*ExecuteBatchRequest) ProtoMessage()               {}
func (*ExecuteBatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *ExecuteBatchRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *ExecuteBatchRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *ExecuteBatchRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *ExecuteBatchRequest) GetQueries() []*BoundQuery {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *ExecuteBatchRequest) GetOptions() *ExecuteOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// ExecuteBatchResponse is the returned value from ExecuteBatch
type ExecuteBatchResponse struct {
	Results []*QueryResult `protobuf:"bytes,1,rep,name=results" json:"results,omitempty"`
}

func (m *ExecuteBatchResponse) Reset()                    { *m = ExecuteBatchResponse{} }
func (m *ExecuteBatchResponse) String() string            { return proto.CompactTextString(m) }
func (*ExecuteBatchResponse) ProtoMessage()               {}
func (*ExecuteBatchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ExecuteBatchResponse) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// StreamExecuteRequest is the payload to StreamExecute
type StreamExecuteRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Query             *BoundQuery     `protobuf:"bytes,4,opt,name=query" json:"query,omitempty"`
	Options           *ExecuteOptions `protobuf:"bytes,5,opt,name=options" json:"options,omitempty"`
}

func (m *StreamExecuteRequest) Reset()                    { *m = StreamExecuteRequest{} }
func (m *StreamExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamExecuteRequest) ProtoMessage()               {}
func (*StreamExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *StreamExecuteRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *StreamExecuteRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *StreamExecuteRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *StreamExecuteRequest) GetQuery() *BoundQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *StreamExecuteRequest) GetOptions() *ExecuteOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// StreamExecuteResponse is the returned value from StreamExecute
type StreamExecuteResponse struct {
	Result *QueryResult `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *StreamExecuteResponse) Reset()                    { *m = StreamExecuteResponse{} }
func (m *StreamExecuteResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamExecuteResponse) ProtoMessage()               {}
func (*StreamExecuteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *StreamExecuteResponse) GetResult() *QueryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// BeginRequest is the payload to Begin
type BeginRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
}

func (m *BeginRequest) Reset()                    { *m = BeginRequest{} }
func (m *BeginRequest) String() string            { return proto.CompactTextString(m) }
func (*BeginRequest) ProtoMessage()               {}
func (*BeginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *BeginRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *BeginRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *BeginRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// BeginResponse is the returned value from Begin
type BeginResponse struct {
	TransactionId int64 `protobuf:"varint,1,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
}

func (m *BeginResponse) Reset()                    { *m = BeginResponse{} }
func (m *BeginResponse) String() string            { return proto.CompactTextString(m) }
func (*BeginResponse) ProtoMessage()               {}
func (*BeginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

// CommitRequest is the payload to Commit
type CommitRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	TransactionId     int64           `protobuf:"varint,4,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
}

func (m *CommitRequest) Reset()                    { *m = CommitRequest{} }
func (m *CommitRequest) String() string            { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()               {}
func (*CommitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *CommitRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *CommitRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *CommitRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// CommitResponse is the returned value from Commit
type CommitResponse struct {
}

func (m *CommitResponse) Reset()                    { *m = CommitResponse{} }
func (m *CommitResponse) String() string            { return proto.CompactTextString(m) }
func (*CommitResponse) ProtoMessage()               {}
func (*CommitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

// RollbackRequest is the payload to Rollback
type RollbackRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	TransactionId     int64           `protobuf:"varint,4,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
}

func (m *RollbackRequest) Reset()                    { *m = RollbackRequest{} }
func (m *RollbackRequest) String() string            { return proto.CompactTextString(m) }
func (*RollbackRequest) ProtoMessage()               {}
func (*RollbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RollbackRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *RollbackRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *RollbackRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// RollbackResponse is the returned value from Rollback
type RollbackResponse struct {
}

func (m *RollbackResponse) Reset()                    { *m = RollbackResponse{} }
func (m *RollbackResponse) String() string            { return proto.CompactTextString(m) }
func (*RollbackResponse) ProtoMessage()               {}
func (*RollbackResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

// PrepareRequest is the payload to Prepare
type PrepareRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	TransactionId     int64           `protobuf:"varint,4,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	Dtid              string          `protobuf:"bytes,5,opt,name=dtid" json:"dtid,omitempty"`
}

func (m *PrepareRequest) Reset()                    { *m = PrepareRequest{} }
func (m *PrepareRequest) String() string            { return proto.CompactTextString(m) }
func (*PrepareRequest) ProtoMessage()               {}
func (*PrepareRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *PrepareRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *PrepareRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *PrepareRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// PrepareResponse is the returned value from Prepare
type PrepareResponse struct {
}

func (m *PrepareResponse) Reset()                    { *m = PrepareResponse{} }
func (m *PrepareResponse) String() string            { return proto.CompactTextString(m) }
func (*PrepareResponse) ProtoMessage()               {}
func (*PrepareResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

// CommitPreparedRequest is the payload to CommitPrepared
type CommitPreparedRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Dtid              string          `protobuf:"bytes,4,opt,name=dtid" json:"dtid,omitempty"`
}

func (m *CommitPreparedRequest) Reset()                    { *m = CommitPreparedRequest{} }
func (m *CommitPreparedRequest) String() string            { return proto.CompactTextString(m) }
func (*CommitPreparedRequest) ProtoMessage()               {}
func (*CommitPreparedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *CommitPreparedRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *CommitPreparedRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *CommitPreparedRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// CommitPreparedResponse is the returned value from CommitPrepared
type CommitPreparedResponse struct {
}

func (m *CommitPreparedResponse) Reset()                    { *m = CommitPreparedResponse{} }
func (m *CommitPreparedResponse) String() string            { return proto.CompactTextString(m) }
func (*CommitPreparedResponse) ProtoMessage()               {}
func (*CommitPreparedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

// RollbackPreparedRequest is the payload to RollbackPrepared
type RollbackPreparedRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	TransactionId     int64           `protobuf:"varint,4,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	Dtid              string          `protobuf:"bytes,5,opt,name=dtid" json:"dtid,omitempty"`
}

func (m *RollbackPreparedRequest) Reset()                    { *m = RollbackPreparedRequest{} }
func (m *RollbackPreparedRequest) String() string            { return proto.CompactTextString(m) }
func (*RollbackPreparedRequest) ProtoMessage()               {}
func (*RollbackPreparedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *RollbackPreparedRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *RollbackPreparedRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *RollbackPreparedRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// RollbackPreparedResponse is the returned value from RollbackPrepared
type RollbackPreparedResponse struct {
}

func (m *RollbackPreparedResponse) Reset()                    { *m = RollbackPreparedResponse{} }
func (m *RollbackPreparedResponse) String() string            { return proto.CompactTextString(m) }
func (*RollbackPreparedResponse) ProtoMessage()               {}
func (*RollbackPreparedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

// CreateTransactionRequest is the payload to CreateTransaction
type CreateTransactionRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Dtid              string          `protobuf:"bytes,4,opt,name=dtid" json:"dtid,omitempty"`
	Participants      []*Target       `protobuf:"bytes,5,rep,name=participants" json:"participants,omitempty"`
}

func (m *CreateTransactionRequest) Reset()                    { *m = CreateTransactionRequest{} }
func (m *CreateTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateTransactionRequest) ProtoMessage()               {}
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *CreateTransactionRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *CreateTransactionRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *CreateTransactionRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *CreateTransactionRequest) GetParticipants() []*Target {
	if m != nil {
		return m.Participants
	}
	return nil
}

// CreateTransactionResponse is the returned value from CreateTransaction
type CreateTransactionResponse struct {
}

func (m *CreateTransactionResponse) Reset()                    { *m = CreateTransactionResponse{} }
func (m *CreateTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateTransactionResponse) ProtoMessage()               {}
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

// StartCommitRequest is the payload to StartCommit
type StartCommitRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	TransactionId     int64           `protobuf:"varint,4,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	Dtid              string          `protobuf:"bytes,5,opt,name=dtid" json:"dtid,omitempty"`
}

func (m *StartCommitRequest) Reset()                    { *m = StartCommitRequest{} }
func (m *StartCommitRequest) String() string            { return proto.CompactTextString(m) }
func (*StartCommitRequest) ProtoMessage()               {}
func (*StartCommitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *StartCommitRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *StartCommitRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *StartCommitRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// StartCommitResponse is the returned value from StartCommit
type StartCommitResponse struct {
}

func (m *StartCommitResponse) Reset()                    { *m = StartCommitResponse{} }
func (m *StartCommitResponse) String() string            { return proto.CompactTextString(m) }
func (*StartCommitResponse) ProtoMessage()               {}
func (*StartCommitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

// SetRollbackRequest is the payload to SetRollback
type SetRollbackRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	TransactionId     int64           `protobuf:"varint,4,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
	Dtid              string          `protobuf:"bytes,5,opt,name=dtid" json:"dtid,omitempty"`
}

func (m *SetRollbackRequest) Reset()                    { *m = SetRollbackRequest{} }
func (m *SetRollbackRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRollbackRequest) ProtoMessage()               {}
func (*SetRollbackRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *SetRollbackRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *SetRollbackRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *SetRollbackRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// SetRollbackResponse is the returned value from SetRollback
type SetRollbackResponse struct {
}

func (m *SetRollbackResponse) Reset()                    { *m = SetRollbackResponse{} }
func (m *SetRollbackResponse) String() string            { return proto.CompactTextString(m) }
func (*SetRollbackResponse) ProtoMessage()               {}
func (*SetRollbackResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

// ConcludeTransactionRequest is the payload to ConcludeTransaction
type ConcludeTransactionRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Dtid              string          `protobuf:"bytes,4,opt,name=dtid" json:"dtid,omitempty"`
}

func (m *ConcludeTransactionRequest) Reset()                    { *m = ConcludeTransactionRequest{} }
func (m *ConcludeTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*ConcludeTransactionRequest) ProtoMessage()               {}
func (*ConcludeTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

func (m *ConcludeTransactionRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *ConcludeTransactionRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *ConcludeTransactionRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// ConcludeTransactionResponse is the returned value from ConcludeTransaction
type ConcludeTransactionResponse struct {
}

func (m *ConcludeTransactionResponse) Reset()                    { *m = ConcludeTransactionResponse{} }
func (m *ConcludeTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*ConcludeTransactionResponse) ProtoMessage()               {}
func (*ConcludeTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

// ReadTransactionRequest is the payload to ReadTransaction
type ReadTransactionRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Dtid              string          `protobuf:"bytes,4,opt,name=dtid" json:"dtid,omitempty"`
}

func (m *ReadTransactionRequest) Reset()                    { *m = ReadTransactionRequest{} }
func (m *ReadTransactionRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadTransactionRequest) ProtoMessage()               {}
func (*ReadTransactionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{39} }

func (m *ReadTransactionRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *ReadTransactionRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *ReadTransactionRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// ReadTransactionResponse is the returned value from ReadTransaction
type ReadTransactionResponse struct {
	Metadata *TransactionMetadata `protobuf:"bytes,1,opt,name=metadata" json:"metadata,omitempty"`
}

func (m *ReadTransactionResponse) Reset()                    { *m = ReadTransactionResponse{} }
func (m *ReadTransactionResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadTransactionResponse) ProtoMessage()               {}
func (*ReadTransactionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{40} }

func (m *ReadTransactionResponse) GetMetadata() *TransactionMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

// BeginExecuteRequest is the payload to BeginExecute
type BeginExecuteRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Query             *BoundQuery     `protobuf:"bytes,4,opt,name=query" json:"query,omitempty"`
	Options           *ExecuteOptions `protobuf:"bytes,5,opt,name=options" json:"options,omitempty"`
}

func (m *BeginExecuteRequest) Reset()                    { *m = BeginExecuteRequest{} }
func (m *BeginExecuteRequest) String() string            { return proto.CompactTextString(m) }
func (*BeginExecuteRequest) ProtoMessage()               {}
func (*BeginExecuteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{41} }

func (m *BeginExecuteRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *BeginExecuteRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *BeginExecuteRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *BeginExecuteRequest) GetQuery() *BoundQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *BeginExecuteRequest) GetOptions() *ExecuteOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// BeginExecuteResponse is the returned value from BeginExecute
type BeginExecuteResponse struct {
	// error contains an application level error if necessary. Note the
	// transaction_id may be set, even when an error is returned, if the begin
	// worked but the execute failed.
	Error  *vtrpc.RPCError `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Result *QueryResult    `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
	// transaction_id might be non-zero even if an error is present.
	TransactionId int64 `protobuf:"varint,3,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
}

func (m *BeginExecuteResponse) Reset()                    { *m = BeginExecuteResponse{} }
func (m *BeginExecuteResponse) String() string            { return proto.CompactTextString(m) }
func (*BeginExecuteResponse) ProtoMessage()               {}
func (*BeginExecuteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{42} }

func (m *BeginExecuteResponse) GetError() *vtrpc.RPCError {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *BeginExecuteResponse) GetResult() *QueryResult {
	if m != nil {
		return m.Result
	}
	return nil
}

// BeginExecuteBatchRequest is the payload to BeginExecuteBatch
type BeginExecuteBatchRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Queries           []*BoundQuery   `protobuf:"bytes,4,rep,name=queries" json:"queries,omitempty"`
	AsTransaction     bool            `protobuf:"varint,5,opt,name=as_transaction,json=asTransaction" json:"as_transaction,omitempty"`
	Options           *ExecuteOptions `protobuf:"bytes,6,opt,name=options" json:"options,omitempty"`
}

func (m *BeginExecuteBatchRequest) Reset()                    { *m = BeginExecuteBatchRequest{} }
func (m *BeginExecuteBatchRequest) String() string            { return proto.CompactTextString(m) }
func (*BeginExecuteBatchRequest) ProtoMessage()               {}
func (*BeginExecuteBatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{43} }

func (m *BeginExecuteBatchRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *BeginExecuteBatchRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *BeginExecuteBatchRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *BeginExecuteBatchRequest) GetQueries() []*BoundQuery {
	if m != nil {
		return m.Queries
	}
	return nil
}

func (m *BeginExecuteBatchRequest) GetOptions() *ExecuteOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

// BeginExecuteBatchResponse is the returned value from BeginExecuteBatch
type BeginExecuteBatchResponse struct {
	// error contains an application level error if necessary. Note the
	// transaction_id may be set, even when an error is returned, if the begin
	// worked but the execute failed.
	Error   *vtrpc.RPCError `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Results []*QueryResult  `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
	// transaction_id might be non-zero even if an error is present.
	TransactionId int64 `protobuf:"varint,3,opt,name=transaction_id,json=transactionId" json:"transaction_id,omitempty"`
}

func (m *BeginExecuteBatchResponse) Reset()                    { *m = BeginExecuteBatchResponse{} }
func (m *BeginExecuteBatchResponse) String() string            { return proto.CompactTextString(m) }
func (*BeginExecuteBatchResponse) ProtoMessage()               {}
func (*BeginExecuteBatchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{44} }

func (m *BeginExecuteBatchResponse) GetError() *vtrpc.RPCError {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *BeginExecuteBatchResponse) GetResults() []*QueryResult {
	if m != nil {
		return m.Results
	}
	return nil
}

// SplitQueryRequest is the payload for SplitQuery sent by VTGate to a VTTablet.
// See vtgate.SplitQueryRequest for more details.
type SplitQueryRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	Query             *BoundQuery     `protobuf:"bytes,4,opt,name=query" json:"query,omitempty"`
	SplitColumn       []string        `protobuf:"bytes,5,rep,name=split_column,json=splitColumn" json:"split_column,omitempty"`
	// Exactly one of the following must be nonzero.
	SplitCount          int64                       `protobuf:"varint,6,opt,name=split_count,json=splitCount" json:"split_count,omitempty"`
	NumRowsPerQueryPart int64                       `protobuf:"varint,8,opt,name=num_rows_per_query_part,json=numRowsPerQueryPart" json:"num_rows_per_query_part,omitempty"`
	Algorithm           SplitQueryRequest_Algorithm `protobuf:"varint,9,opt,name=algorithm,enum=query.SplitQueryRequest_Algorithm" json:"algorithm,omitempty"`
}

func (m *SplitQueryRequest) Reset()                    { *m = SplitQueryRequest{} }
func (m *SplitQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*SplitQueryRequest) ProtoMessage()               {}
func (*SplitQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{45} }

func (m *SplitQueryRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *SplitQueryRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *SplitQueryRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *SplitQueryRequest) GetQuery() *BoundQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

// QuerySplit represents one query to execute on the tablet
type QuerySplit struct {
	// query is the query to execute
	Query *BoundQuery `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	// row_count is the approximate row count the query will return
	RowCount int64 `protobuf:"varint,2,opt,name=row_count,json=rowCount" json:"row_count,omitempty"`
}

func (m *QuerySplit) Reset()                    { *m = QuerySplit{} }
func (m *QuerySplit) String() string            { return proto.CompactTextString(m) }
func (*QuerySplit) ProtoMessage()               {}
func (*QuerySplit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{46} }

func (m *QuerySplit) GetQuery() *BoundQuery {
	if m != nil {
		return m.Query
	}
	return nil
}

// SplitQueryResponse is returned by SplitQuery and represents all the queries
// to execute in order to get the entire data set.
type SplitQueryResponse struct {
	Queries []*QuerySplit `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (m *SplitQueryResponse) Reset()                    { *m = SplitQueryResponse{} }
func (m *SplitQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*SplitQueryResponse) ProtoMessage()               {}
func (*SplitQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{47} }

func (m *SplitQueryResponse) GetQueries() []*QuerySplit {
	if m != nil {
		return m.Queries
	}
	return nil
}

// StreamHealthRequest is the payload for StreamHealth
type StreamHealthRequest struct {
}

func (m *StreamHealthRequest) Reset()                    { *m = StreamHealthRequest{} }
func (m *StreamHealthRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamHealthRequest) ProtoMessage()               {}
func (*StreamHealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{48} }

// RealtimeStats contains information about the tablet status
type RealtimeStats struct {
	// health_error is the last error we got from health check,
	// or empty is the server is healthy. This is used for subset selection,
	// we do not send queries to servers that are not healthy.
	HealthError string `protobuf:"bytes,1,opt,name=health_error,json=healthError" json:"health_error,omitempty"`
	// seconds_behind_master is populated for slaves only. It indicates
	// how far behind on (MySQL) replication a slave currently is.  It is used
	// by clients for subset selection (so we don't try to send traffic
	// to tablets that are too far behind).
	// NOTE: This field must not be evaluated if "health_error" is not empty.
	// TODO(mberlin): Let's switch it to int64 instead?
	SecondsBehindMaster uint32 `protobuf:"varint,2,opt,name=seconds_behind_master,json=secondsBehindMaster" json:"seconds_behind_master,omitempty"`
	// bin_log_players_count is the number of currently running binlog players.
	// if the value is 0, it means that filtered replication is currently not
	// running on the tablet. If >0, filtered replication is running.
	// NOTE: This field must not be evaluated if "health_error" is not empty.
	BinlogPlayersCount int32 `protobuf:"varint,3,opt,name=binlog_players_count,json=binlogPlayersCount" json:"binlog_players_count,omitempty"`
	// seconds_behind_master_filtered_replication is populated for the receiving
	// master of an ongoing filtered replication only.
	// It specifies how far the receiving master lags behind the sending master.
	// NOTE: This field must not be evaluated if "health_error" is not empty.
	// NOTE: This field must not be evaluated if "bin_log_players_count" is 0.
	SecondsBehindMasterFilteredReplication int64 `protobuf:"varint,4,opt,name=seconds_behind_master_filtered_replication,json=secondsBehindMasterFilteredReplication" json:"seconds_behind_master_filtered_replication,omitempty"`
	// cpu_usage is used for load-based balancing
	CpuUsage float64 `protobuf:"fixed64,5,opt,name=cpu_usage,json=cpuUsage" json:"cpu_usage,omitempty"`
	// qps is the average QPS (queries per second) rate in the last XX seconds
	// where XX is usually 60 (See query_service_stats.go).
	Qps float64 `protobuf:"fixed64,6,opt,name=qps" json:"qps,omitempty"`
}

func (m *RealtimeStats) Reset()                    { *m = RealtimeStats{} }
func (m *RealtimeStats) String() string            { return proto.CompactTextString(m) }
func (*RealtimeStats) ProtoMessage()               {}
func (*RealtimeStats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{49} }

// StreamHealthResponse is streamed by StreamHealth on a regular basis
type StreamHealthResponse struct {
	// target is the current server type. Only queries with that exact Target
	// record will be accepted.
	Target *Target `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
	// serving is true iff the tablet is serving. A tablet may not be serving
	// if filtered replication is enabled on a master for instance,
	// or if a replica should not be used because the keyspace is being resharded.
	Serving bool `protobuf:"varint,2,opt,name=serving" json:"serving,omitempty"`
	// tablet_externally_reparented_timestamp contains the last time
	// tabletmanager.TabletExternallyReparented was called on this tablet,
	// or 0 if it was never called. This is meant to differentiate two tablets
	// that report a target.TabletType of MASTER, only the one with the latest
	// timestamp should be trusted.
	TabletExternallyReparentedTimestamp int64 `protobuf:"varint,3,opt,name=tablet_externally_reparented_timestamp,json=tabletExternallyReparentedTimestamp" json:"tablet_externally_reparented_timestamp,omitempty"`
	// realtime_stats contains information about the tablet status
	RealtimeStats *RealtimeStats `protobuf:"bytes,4,opt,name=realtime_stats,json=realtimeStats" json:"realtime_stats,omitempty"`
}

func (m *StreamHealthResponse) Reset()                    { *m = StreamHealthResponse{} }
func (m *StreamHealthResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamHealthResponse) ProtoMessage()               {}
func (*StreamHealthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{50} }

func (m *StreamHealthResponse) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *StreamHealthResponse) GetRealtimeStats() *RealtimeStats {
	if m != nil {
		return m.RealtimeStats
	}
	return nil
}

// UpdateStreamRequest is the payload for UpdateStream. At most one of
// position and timestamp can be set. If neither is set, we will start
// streaming from the current binlog position.
type UpdateStreamRequest struct {
	EffectiveCallerId *vtrpc.CallerID `protobuf:"bytes,1,opt,name=effective_caller_id,json=effectiveCallerId" json:"effective_caller_id,omitempty"`
	ImmediateCallerId *VTGateCallerID `protobuf:"bytes,2,opt,name=immediate_caller_id,json=immediateCallerId" json:"immediate_caller_id,omitempty"`
	Target            *Target         `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
	// If position is set, we will start the streaming from that replication
	// position. Incompatible with timestamp.
	Position string `protobuf:"bytes,4,opt,name=position" json:"position,omitempty"`
	// If timestamp is set, we will start the streaming from the first
	// event in the binlogs that have that timestamp. Incompatible with position.
	Timestamp int64 `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *UpdateStreamRequest) Reset()                    { *m = UpdateStreamRequest{} }
func (m *UpdateStreamRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateStreamRequest) ProtoMessage()               {}
func (*UpdateStreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{51} }

func (m *UpdateStreamRequest) GetEffectiveCallerId() *vtrpc.CallerID {
	if m != nil {
		return m.EffectiveCallerId
	}
	return nil
}

func (m *UpdateStreamRequest) GetImmediateCallerId() *VTGateCallerID {
	if m != nil {
		return m.ImmediateCallerId
	}
	return nil
}

func (m *UpdateStreamRequest) GetTarget() *Target {
	if m != nil {
		return m.Target
	}
	return nil
}

// UpdateStreamResponse is returned by UpdateStream
type UpdateStreamResponse struct {
	Event *StreamEvent `protobuf:"bytes,1,opt,name=event" json:"event,omitempty"`
}

func (m *UpdateStreamResponse) Reset()                    { *m = UpdateStreamResponse{} }
func (m *UpdateStreamResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateStreamResponse) ProtoMessage()               {}
func (*UpdateStreamResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{52} }

func (m *UpdateStreamResponse) GetEvent() *StreamEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

// TransactionMetadata contains the metadata for a distributed transaction.
type TransactionMetadata struct {
	Dtid         string           `protobuf:"bytes,1,opt,name=dtid" json:"dtid,omitempty"`
	State        TransactionState `protobuf:"varint,2,opt,name=state,enum=query.TransactionState" json:"state,omitempty"`
	TimeCreated  int64            `protobuf:"varint,3,opt,name=time_created,json=timeCreated" json:"time_created,omitempty"`
	Participants []*Target        `protobuf:"bytes,4,rep,name=participants" json:"participants,omitempty"`
}

func (m *TransactionMetadata) Reset()                    { *m = TransactionMetadata{} }
func (m *TransactionMetadata) String() string            { return proto.CompactTextString(m) }
func (*TransactionMetadata) ProtoMessage()               {}
func (*TransactionMetadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{53} }

func (m *TransactionMetadata) GetParticipants() []*Target {
	if m != nil {
		return m.Participants
	}
	return nil
}

func init() {
	proto.RegisterType((*Target)(nil), "query.Target")
	proto.RegisterType((*VTGateCallerID)(nil), "query.VTGateCallerID")
	proto.RegisterType((*EventToken)(nil), "query.EventToken")
	proto.RegisterType((*Value)(nil), "query.Value")
	proto.RegisterType((*BindVariable)(nil), "query.BindVariable")
	proto.RegisterType((*BoundQuery)(nil), "query.BoundQuery")
	proto.RegisterType((*ExecuteOptions)(nil), "query.ExecuteOptions")
	proto.RegisterType((*Field)(nil), "query.Field")
	proto.RegisterType((*Row)(nil), "query.Row")
	proto.RegisterType((*ResultExtras)(nil), "query.ResultExtras")
	proto.RegisterType((*QueryResult)(nil), "query.QueryResult")
	proto.RegisterType((*StreamEvent)(nil), "query.StreamEvent")
	proto.RegisterType((*StreamEvent_Statement)(nil), "query.StreamEvent.Statement")
	proto.RegisterType((*ExecuteRequest)(nil), "query.ExecuteRequest")
	proto.RegisterType((*ExecuteResponse)(nil), "query.ExecuteResponse")
	proto.RegisterType((*ResultWithError)(nil), "query.ResultWithError")
	proto.RegisterType((*ExecuteBatchRequest)(nil), "query.ExecuteBatchRequest")
	proto.RegisterType((*ExecuteBatchResponse)(nil), "query.ExecuteBatchResponse")
	proto.RegisterType((*StreamExecuteRequest)(nil), "query.StreamExecuteRequest")
	proto.RegisterType((*StreamExecuteResponse)(nil), "query.StreamExecuteResponse")
	proto.RegisterType((*BeginRequest)(nil), "query.BeginRequest")
	proto.RegisterType((*BeginResponse)(nil), "query.BeginResponse")
	proto.RegisterType((*CommitRequest)(nil), "query.CommitRequest")
	proto.RegisterType((*CommitResponse)(nil), "query.CommitResponse")
	proto.RegisterType((*RollbackRequest)(nil), "query.RollbackRequest")
	proto.RegisterType((*RollbackResponse)(nil), "query.RollbackResponse")
	proto.RegisterType((*PrepareRequest)(nil), "query.PrepareRequest")
	proto.RegisterType((*PrepareResponse)(nil), "query.PrepareResponse")
	proto.RegisterType((*CommitPreparedRequest)(nil), "query.CommitPreparedRequest")
	proto.RegisterType((*CommitPreparedResponse)(nil), "query.CommitPreparedResponse")
	proto.RegisterType((*RollbackPreparedRequest)(nil), "query.RollbackPreparedRequest")
	proto.RegisterType((*RollbackPreparedResponse)(nil), "query.RollbackPreparedResponse")
	proto.RegisterType((*CreateTransactionRequest)(nil), "query.CreateTransactionRequest")
	proto.RegisterType((*CreateTransactionResponse)(nil), "query.CreateTransactionResponse")
	proto.RegisterType((*StartCommitRequest)(nil), "query.StartCommitRequest")
	proto.RegisterType((*StartCommitResponse)(nil), "query.StartCommitResponse")
	proto.RegisterType((*SetRollbackRequest)(nil), "query.SetRollbackRequest")
	proto.RegisterType((*SetRollbackResponse)(nil), "query.SetRollbackResponse")
	proto.RegisterType((*ConcludeTransactionRequest)(nil), "query.ConcludeTransactionRequest")
	proto.RegisterType((*ConcludeTransactionResponse)(nil), "query.ConcludeTransactionResponse")
	proto.RegisterType((*ReadTransactionRequest)(nil), "query.ReadTransactionRequest")
	proto.RegisterType((*ReadTransactionResponse)(nil), "query.ReadTransactionResponse")
	proto.RegisterType((*BeginExecuteRequest)(nil), "query.BeginExecuteRequest")
	proto.RegisterType((*BeginExecuteResponse)(nil), "query.BeginExecuteResponse")
	proto.RegisterType((*BeginExecuteBatchRequest)(nil), "query.BeginExecuteBatchRequest")
	proto.RegisterType((*BeginExecuteBatchResponse)(nil), "query.BeginExecuteBatchResponse")
	proto.RegisterType((*SplitQueryRequest)(nil), "query.SplitQueryRequest")
	proto.RegisterType((*QuerySplit)(nil), "query.QuerySplit")
	proto.RegisterType((*SplitQueryResponse)(nil), "query.SplitQueryResponse")
	proto.RegisterType((*StreamHealthRequest)(nil), "query.StreamHealthRequest")
	proto.RegisterType((*RealtimeStats)(nil), "query.RealtimeStats")
	proto.RegisterType((*StreamHealthResponse)(nil), "query.StreamHealthResponse")
	proto.RegisterType((*UpdateStreamRequest)(nil), "query.UpdateStreamRequest")
	proto.RegisterType((*UpdateStreamResponse)(nil), "query.UpdateStreamResponse")
	proto.RegisterType((*TransactionMetadata)(nil), "query.TransactionMetadata")
	proto.RegisterEnum("query.MySqlFlag", MySqlFlag_name, MySqlFlag_value)
	proto.RegisterEnum("query.Flag", Flag_name, Flag_value)
	proto.RegisterEnum("query.Type", Type_name, Type_value)
	proto.RegisterEnum("query.TransactionState", TransactionState_name, TransactionState_value)
	proto.RegisterEnum("query.StreamEvent_Statement_Category", StreamEvent_Statement_Category_name, StreamEvent_Statement_Category_value)
	proto.RegisterEnum("query.SplitQueryRequest_Algorithm", SplitQueryRequest_Algorithm_name, SplitQueryRequest_Algorithm_value)
}

func init() { proto.RegisterFile("query.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 2703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xec, 0x1a, 0x49, 0x93, 0x1b, 0x57,
	0xd9, 0xad, 0x65, 0x46, 0xfa, 0x34, 0x92, 0xdf, 0x3c, 0xcd, 0xd8, 0xca, 0x38, 0x21, 0x43, 0x27,
	0x4e, 0x06, 0x27, 0x0c, 0xce, 0x78, 0x30, 0xa9, 0xb0, 0x59, 0xa3, 0xe9, 0x71, 0x84, 0xb5, 0xf9,
	0xa9, 0xe5, 0xe0, 0x54, 0xaa, 0xba, 0x7a, 0xa4, 0x67, 0x4d, 0xd7, 0x48, 0xdd, 0x72, 0xf7, 0xd3,
	0xd8, 0xba, 0x19, 0xc2, 0x16, 0xd6, 0xb0, 0x86, 0xa5, 0x08, 0x54, 0x71, 0xe7, 0x1f, 0x50, 0x45,
	0xf1, 0x03, 0xb8, 0x71, 0x81, 0x03, 0x27, 0x8a, 0xca, 0x8d, 0x33, 0x07, 0x8a, 0x7a, 0x4b, 0xb7,
	0x5a, 0x33, 0x4a, 0xec, 0x04, 0x2e, 0x76, 0x72, 0xd2, 0xfb, 0x96, 0x7e, 0xdf, 0xfe, 0xbd, 0x4d,
	0x90, 0xbb, 0x3d, 0xa6, 0xfe, 0x64, 0x73, 0xe4, 0x7b, 0xcc, 0xc3, 0x69, 0x01, 0xac, 0x15, 0x98,
	0x37, 0xf2, 0x7a, 0x36, 0xb3, 0x25, 0x7a, 0x2d, 0x77, 0xc4, 0xfc, 0x51, 0x57, 0x02, 0xfa, 0x6d,
	0x58, 0x30, 0x6d, 0xbf, 0x4f, 0x19, 0x5e, 0x83, 0xcc, 0x21, 0x9d, 0x04, 0x23, 0xbb, 0x4b, 0x4b,
	0xda, 0xba, 0xb6, 0x91, 0x25, 0x11, 0x8c, 0x57, 0x20, 0x1d, 0x1c, 0xd8, 0x7e, 0xaf, 0x94, 0x10,
	0x04, 0x09, 0xe0, 0x4f, 0x43, 0x8e, 0xd9, 0xfb, 0x03, 0xca, 0x2c, 0x36, 0x19, 0xd1, 0x52, 0x72,
	0x5d, 0xdb, 0x28, 0x6c, 0xad, 0x6c, 0x46, 0xe2, 0x4c, 0x41, 0x34, 0x27, 0x23, 0x4a, 0x80, 0x45,
	0x63, 0xfd, 0x79, 0x28, 0xdc, 0x30, 0xaf, 0xda, 0x8c, 0x56, 0xec, 0xc1, 0x80, 0xfa, 0xd5, 0x5d,
	0x2e, 0x7a, 0x1c, 0x50, 0xdf, 0xb5, 0x87, 0x91, 0xe8, 0x10, 0xd6, 0x5f, 0x03, 0x30, 0x8e, 0xa8,
	0xcb, 0x4c, 0xef, 0x90, 0xba, 0xf8, 0x71, 0xc8, 0x32, 0x67, 0x48, 0x03, 0x66, 0x0f, 0x47, 0x82,
	0x35, 0x49, 0xa6, 0x88, 0x77, 0x51, 0x73, 0x0d, 0x32, 0x23, 0x2f, 0x70, 0x98, 0xe3, 0xb9, 0x42,
	0xc7, 0x2c, 0x89, 0x60, 0xfd, 0x0b, 0x90, 0xbe, 0x61, 0x0f, 0xc6, 0x14, 0x3f, 0x09, 0x29, 0x61,
	0x84, 0x26, 0x8c, 0xc8, 0x6d, 0x4a, 0x3f, 0x0a, 0xdd, 0x05, 0x81, 0xcf, 0x7d, 0xc4, 0x39, 0xc5,
	0xdc, 0x4b, 0x44, 0x02, 0xfa, 0x21, 0x2c, 0xed, 0x38, 0x6e, 0xef, 0x86, 0xed, 0x3b, 0xdc, 0xc0,
	0x0f, 0x38, 0x0d, 0x7e, 0x1a, 0x16, 0xc4, 0x20, 0x28, 0x25, 0xd7, 0x93, 0x1b, 0xb9, 0xad, 0x25,
	0xf5, 0xa1, 0xd0, 0x8d, 0x28, 0x9a, 0xfe, 0x27, 0x0d, 0x60, 0xc7, 0x1b, 0xbb, 0xbd, 0xeb, 0x9c,
	0x88, 0x11, 0x24, 0x83, 0xdb, 0x03, 0xe5, 0x30, 0x3e, 0xc4, 0xd7, 0xa0, 0xb0, 0xef, 0xb8, 0x3d,
	0xeb, 0x48, 0xa9, 0x13, 0x94, 0x12, 0x62, 0xba, 0xa7, 0xd5, 0x74, 0xd3, 0x8f, 0x37, 0xe3, 0x5a,
	0x07, 0x86, 0xcb, 0xfc, 0x09, 0xc9, 0xef, 0xc7, 0x71, 0x6b, 0x1d, 0xc0, 0x27, 0x99, 0xb8, 0xd0,
	0x43, 0x3a, 0x09, 0x85, 0x1e, 0xd2, 0x09, 0xfe, 0x44, 0xdc, 0xa2, 0xdc, 0x56, 0x31, 0x94, 0x15,
	0xfb, 0x56, 0x99, 0xf9, 0x52, 0xe2, 0x45, 0x4d, 0x7f, 0x47, 0x83, 0x82, 0x71, 0x97, 0x76, 0xc7,
	0x8c, 0x36, 0x47, 0x3c, 0x06, 0x01, 0xde, 0x84, 0x22, 0xbd, 0xdb, 0x1d, 0x8c, 0x7b, 0xd4, 0xba,
	0xe5, 0xd0, 0x41, 0xcf, 0xe2, 0x81, 0x0f, 0x84, 0x8c, 0x0c, 0x59, 0x56, 0xa4, 0x3d, 0x4e, 0x69,
	0x70, 0x02, 0xe7, 0x77, 0x5c, 0xc9, 0x4f, 0x79, 0x6a, 0x58, 0x8c, 0xe7, 0x86, 0x90, 0x9f, 0x21,
	0xcb, 0x8a, 0x14, 0x4b, 0x9a, 0x32, 0x14, 0xbb, 0xde, 0x70, 0x64, 0xfb, 0xb3, 0xfc, 0x49, 0xa1,
	0xef, 0xb2, 0xd2, 0x77, 0xca, 0x4f, 0x96, 0x15, 0x77, 0x6c, 0x8a, 0x6d, 0x38, 0x33, 0xab, 0xe2,
	0x90, 0x32, 0x9b, 0x27, 0x79, 0x29, 0x25, 0xa4, 0xae, 0xc4, 0xb5, 0xac, 0x2b, 0x9a, 0xfe, 0x56,
	0x02, 0xd2, 0x02, 0x83, 0x31, 0xa4, 0x62, 0xd9, 0x2d, 0xc6, 0x51, 0xae, 0x24, 0xde, 0x23, 0x57,
	0x44, 0xd9, 0xa8, 0xac, 0x95, 0x00, 0x3e, 0x07, 0x59, 0xcf, 0xef, 0x5b, 0x92, 0x92, 0x92, 0xf9,
	0xec, 0xf9, 0x7d, 0x51, 0x6c, 0x3c, 0xd7, 0xb9, 0xe4, 0x7d, 0x3b, 0xa0, 0xa5, 0xb4, 0xa4, 0x85,
	0x30, 0x7e, 0x0c, 0x38, 0x9f, 0x70, 0x6e, 0x69, 0x41, 0xd0, 0x16, 0x3d, 0xbf, 0xcf, 0x5d, 0x8a,
	0x9f, 0x82, 0x7c, 0xd7, 0x1b, 0x8c, 0x87, 0xae, 0x35, 0xa0, 0x6e, 0x9f, 0x1d, 0x94, 0x16, 0xd7,
	0xb5, 0x8d, 0x14, 0x59, 0x92, 0xc8, 0x9a, 0xc0, 0xe1, 0x12, 0x2c, 0x76, 0x0f, 0x6c, 0x3f, 0xa0,
	0xac, 0x94, 0x59, 0xd7, 0x36, 0xf2, 0x24, 0x04, 0x85, 0x54, 0xda, 0x75, 0x86, 0xf6, 0x20, 0x28,
	0x65, 0x05, 0x29, 0x82, 0xb9, 0x11, 0xb7, 0x06, 0x76, 0x3f, 0x28, 0x81, 0x20, 0x48, 0x40, 0xff,
	0x0c, 0x24, 0x89, 0x77, 0x87, 0x4f, 0x29, 0x05, 0xf2, 0x68, 0x27, 0x37, 0x30, 0x09, 0x41, 0x7c,
	0x26, 0xaa, 0x08, 0x59, 0x28, 0x61, 0x0d, 0xbc, 0x06, 0x4b, 0x84, 0x06, 0xe3, 0x01, 0x33, 0xee,
	0x32, 0xdf, 0x0e, 0xf0, 0x16, 0xe4, 0xe2, 0x31, 0xd5, 0xde, 0x2d, 0xa6, 0x40, 0xa7, 0xc1, 0x2c,
	0xc1, 0xe2, 0x2d, 0x9f, 0x06, 0x07, 0xd4, 0x57, 0x39, 0x13, 0x82, 0xbc, 0xc2, 0x72, 0xa2, 0x3e,
	0xa4, 0x0c, 0x5e, 0x97, 0x22, 0xdc, 0x52, 0xbd, 0x69, 0x5d, 0x8a, 0xa0, 0x12, 0x45, 0xe3, 0xde,
	0xf3, 0xbd, 0x3b, 0x81, 0x65, 0xdf, 0xba, 0x45, 0xbb, 0x8c, 0xca, 0xf6, 0x93, 0x22, 0x4b, 0x1c,
	0x59, 0x56, 0x38, 0x1e, 0x36, 0xc7, 0x0d, 0xa8, 0xcf, 0x2c, 0xa7, 0x27, 0x02, 0x9a, 0x22, 0x19,
	0x89, 0xa8, 0xf6, 0xf0, 0xc7, 0x20, 0xc5, 0x99, 0x4b, 0x29, 0x21, 0x05, 0x94, 0x14, 0xe2, 0xdd,
	0x21, 0x02, 0x8f, 0x9f, 0x83, 0x05, 0x2a, 0xec, 0x15, 0x41, 0x9d, 0x16, 0x59, 0xdc, 0x15, 0x44,
	0xb1, 0xe8, 0xbf, 0x4d, 0x42, 0xae, 0xcd, 0x7c, 0x6a, 0x0f, 0x85, 0xfd, 0xf8, 0x73, 0x00, 0x01,
	0xb3, 0x19, 0x1d, 0x52, 0x97, 0x85, 0x86, 0x3c, 0xae, 0x26, 0x88, 0xf1, 0x6d, 0xb6, 0x43, 0x26,
	0x12, 0xe3, 0x3f, 0xee, 0xe0, 0xc4, 0x03, 0x38, 0x78, 0xed, 0xed, 0x04, 0x64, 0xa3, 0xd9, 0x70,
	0x19, 0x32, 0x5d, 0x9b, 0xd1, 0xbe, 0xe7, 0x4f, 0x54, 0x5f, 0x3c, 0xff, 0x5e, 0xd2, 0x37, 0x2b,
	0x8a, 0x99, 0x44, 0x9f, 0xe1, 0x27, 0x40, 0x2e, 0x20, 0x32, 0x79, 0x65, 0x77, 0xcf, 0x0a, 0x8c,
	0x48, 0xdf, 0x97, 0x00, 0x8f, 0x7c, 0x67, 0x68, 0xfb, 0x13, 0xeb, 0x90, 0x4e, 0x2c, 0x15, 0xb2,
	0xe4, 0x9c, 0x90, 0x21, 0xc5, 0x77, 0x8d, 0x4e, 0xf6, 0x64, 0xf0, 0x5e, 0x9c, 0xfd, 0x56, 0x25,
	0xdd, 0xc9, 0x40, 0xc4, 0xbe, 0x14, 0x5d, 0x39, 0x08, 0xfb, 0x6f, 0x5a, 0xe4, 0x27, 0x1f, 0xea,
	0xcf, 0x42, 0x26, 0x54, 0x1e, 0x67, 0x21, 0x6d, 0xf8, 0xbe, 0xe7, 0xa3, 0x53, 0x78, 0x11, 0x92,
	0xbb, 0xf5, 0x1a, 0xd2, 0xc4, 0x60, 0xb7, 0x86, 0x12, 0xfa, 0x1f, 0x13, 0x51, 0x13, 0x24, 0xf4,
	0xf6, 0x98, 0x06, 0x0c, 0x7f, 0x11, 0x8a, 0x54, 0xe4, 0x8a, 0x73, 0x44, 0xad, 0xae, 0x58, 0x19,
	0x79, 0xa6, 0xc8, 0x84, 0x3e, 0xbd, 0x29, 0xd7, 0xec, 0x70, 0xc5, 0x24, 0xcb, 0x11, 0xaf, 0x42,
	0xf5, 0xb0, 0x01, 0x45, 0x67, 0x38, 0xa4, 0x3d, 0xc7, 0x66, 0xf1, 0x09, 0x64, 0xc0, 0x56, 0xc3,
	0x05, 0x65, 0x66, 0xe1, 0x25, 0xcb, 0xd1, 0x17, 0xd1, 0x34, 0xe7, 0x61, 0x81, 0x89, 0x0d, 0x81,
	0xea, 0x8f, 0xf9, 0xb0, 0x2f, 0x09, 0x24, 0x51, 0x44, 0xfc, 0x2c, 0xc8, 0xdd, 0x85, 0xe8, 0x40,
	0xd3, 0x84, 0x98, 0xae, 0x30, 0x44, 0xd2, 0xf1, 0x79, 0x28, 0x30, 0xdf, 0x76, 0x03, 0xbb, 0xcb,
	0x9b, 0x3d, 0xd7, 0x28, 0x2d, 0x96, 0xed, 0x7c, 0x0c, 0x5b, 0xed, 0xe1, 0x4f, 0xc1, 0xa2, 0x27,
	0x97, 0x03, 0xd1, 0x9b, 0xa6, 0x1a, 0xcf, 0xae, 0x15, 0x24, 0xe4, 0xd2, 0x3f, 0x0f, 0xa7, 0x23,
	0x0f, 0x06, 0x23, 0xcf, 0x0d, 0x28, 0xbe, 0x00, 0x0b, 0xbe, 0x28, 0x08, 0xe5, 0x35, 0xac, 0xa6,
	0x88, 0x55, 0x34, 0x51, 0x1c, 0x7a, 0x0f, 0x4e, 0x4b, 0xcc, 0x2b, 0x0e, 0x3b, 0x10, 0x81, 0xc2,
	0xe7, 0x21, 0x4d, 0xf9, 0xe0, 0x98, 0xcf, 0x49, 0xab, 0x22, 0xe8, 0x44, 0x52, 0x63, 0x52, 0x12,
	0xf7, 0x95, 0xf2, 0xaf, 0x04, 0x14, 0x95, 0x96, 0x3b, 0x36, 0xeb, 0x1e, 0x3c, 0xa4, 0xc1, 0x7e,
	0x0e, 0x16, 0x39, 0xde, 0x89, 0x0a, 0x63, 0x4e, 0xb8, 0x43, 0x0e, 0x1e, 0x70, 0x3b, 0xb0, 0x62,
	0xd1, 0x15, 0x01, 0xcf, 0x90, 0xbc, 0x1d, 0x98, 0x53, 0xe4, 0x9c, 0xbc, 0x58, 0xb8, 0x4f, 0x5e,
	0x2c, 0x3e, 0x50, 0x5e, 0xec, 0xc2, 0xca, 0xac, 0xc7, 0x55, 0x72, 0x3c, 0x0f, 0x8b, 0x32, 0x28,
	0x61, 0x0b, 0x9c, 0x17, 0xb7, 0x90, 0x45, 0xff, 0x4d, 0x02, 0x56, 0x54, 0x77, 0xfa, 0x70, 0x94,
	0x69, 0xcc, 0xcf, 0xe9, 0x07, 0xf2, 0x73, 0x05, 0x56, 0x8f, 0x39, 0xe8, 0x03, 0x54, 0xe1, 0x1f,
	0x34, 0x58, 0xda, 0xa1, 0x7d, 0xc7, 0x7d, 0x38, 0xdd, 0xab, 0x5f, 0x86, 0xbc, 0x52, 0x5f, 0x19,
	0x7f, 0x32, 0xab, 0xb5, 0x39, 0x59, 0xad, 0xff, 0x43, 0x83, 0x7c, 0xc5, 0x1b, 0x0e, 0x1d, 0xf6,
	0x90, 0xe6, 0xd5, 0x49, 0x3b, 0x53, 0xf3, 0xec, 0x44, 0x50, 0x08, 0xcd, 0x94, 0x0e, 0xd2, 0xff,
	0xa9, 0xc1, 0x69, 0xe2, 0x0d, 0x06, 0xfb, 0x76, 0xf7, 0xf0, 0xd1, 0xb6, 0x1d, 0x03, 0x9a, 0x1a,
	0xaa, 0xac, 0xff, 0xb7, 0x06, 0x85, 0x96, 0x4f, 0xf9, 0xe1, 0xe2, 0x91, 0x36, 0x9e, 0x9f, 0x77,
	0x7a, 0x4c, 0xad, 0xf5, 0x59, 0x22, 0xc6, 0xfa, 0x32, 0x9c, 0x8e, 0x6c, 0x57, 0xfe, 0xf8, 0xab,
	0x06, 0xab, 0x32, 0x41, 0x14, 0xa5, 0xf7, 0x90, 0xba, 0x25, 0xb4, 0x37, 0x15, 0xb3, 0xb7, 0x04,
	0x67, 0x8e, 0xdb, 0xa6, 0xcc, 0x7e, 0x3d, 0x01, 0x67, 0xc3, 0xdc, 0x78, 0xc8, 0x0d, 0xff, 0x1f,
	0xf2, 0x61, 0x0d, 0x4a, 0x27, 0x9d, 0xa0, 0x3c, 0xf4, 0x66, 0x02, 0x4a, 0x15, 0x9f, 0xda, 0x8c,
	0xc6, 0xf6, 0x0c, 0x8f, 0x4e, 0x6e, 0xe0, 0x17, 0x60, 0x69, 0x64, 0xfb, 0xcc, 0xe9, 0x3a, 0x23,
	0x9b, 0x9f, 0xca, 0xd2, 0x62, 0x4b, 0x72, 0x6c, 0x82, 0x19, 0x16, 0xfd, 0x1c, 0x3c, 0x36, 0xc7,
	0x23, 0xca, 0x5f, 0xff, 0xd1, 0x00, 0xb7, 0x99, 0xed, 0xb3, 0x0f, 0xc1, 0xaa, 0x32, 0x37, 0x99,
	0x56, 0xa1, 0x38, 0x63, 0x7f, 0xdc, 0x2f, 0x94, 0x7d, 0x28, 0x56, 0x9c, 0x77, 0xf5, 0x4b, 0xdc,
	0x7e, 0xe5, 0x97, 0xbf, 0x6b, 0xb0, 0x56, 0xf1, 0xe4, 0x4d, 0xd9, 0x23, 0x59, 0x61, 0xfa, 0x13,
	0x70, 0x6e, 0xae, 0x81, 0xca, 0x01, 0x7f, 0xd3, 0xe0, 0x0c, 0xa1, 0x76, 0xef, 0xd1, 0x34, 0xfe,
	0x3a, 0x9c, 0x3d, 0x61, 0x9c, 0xda, 0xa1, 0x5e, 0x86, 0x4c, 0x74, 0x77, 0x29, 0x4d, 0x5a, 0x0b,
	0xe7, 0x9d, 0x72, 0x87, 0x37, 0x98, 0x24, 0xe2, 0xd5, 0xdf, 0x4e, 0x40, 0x51, 0xec, 0x75, 0x3f,
	0x3a, 0x10, 0xcd, 0x3f, 0x10, 0xbd, 0xa9, 0xc1, 0xca, 0xac, 0x83, 0xa2, 0x33, 0xc1, 0xff, 0xfb,
	0x5e, 0x61, 0x4e, 0x43, 0x48, 0xce, 0xdb, 0x82, 0xfe, 0x39, 0x01, 0xa5, 0xb8, 0x4a, 0x1f, 0xdd,
	0x41, 0xcc, 0xde, 0x41, 0xbc, 0xef, 0x4b, 0xa7, 0xb7, 0x34, 0x78, 0x6c, 0x8e, 0x43, 0xdf, 0x5f,
	0xa0, 0x63, 0x37, 0x11, 0x89, 0xfb, 0xde, 0x44, 0x3c, 0x68, 0xa8, 0xff, 0x92, 0x84, 0xe5, 0xf6,
	0x68, 0xe0, 0x30, 0x35, 0xc9, 0xa3, 0x5d, 0x9c, 0x1f, 0x87, 0xa5, 0x80, 0x1b, 0x6b, 0xc9, 0x07,
	0x0a, 0xb1, 0x7d, 0xca, 0x92, 0x9c, 0xc0, 0x55, 0x04, 0x0a, 0x3f, 0x09, 0xb9, 0x90, 0x65, 0xec,
	0x32, 0x75, 0xb9, 0x04, 0x8a, 0x63, 0xec, 0x32, 0xbc, 0x0d, 0x67, 0xdd, 0xf1, 0xd0, 0x12, 0x37,
	0xf7, 0x23, 0xea, 0x5b, 0x62, 0x66, 0x8b, 0x6f, 0xb9, 0xc4, 0xf3, 0x46, 0x92, 0x14, 0xdd, 0xf1,
	0x90, 0x78, 0x77, 0x82, 0x16, 0xf5, 0x85, 0xf0, 0x96, 0xed, 0x33, 0x7c, 0x05, 0xb2, 0xf6, 0xa0,
	0xef, 0xf9, 0x0e, 0x3b, 0x18, 0x8a, 0xb7, 0x8e, 0xc2, 0x96, 0x1e, 0xde, 0x66, 0x1f, 0x77, 0xff,
	0x66, 0x39, 0xe4, 0x24, 0xd3, 0x8f, 0xf4, 0xe7, 0x21, 0x1b, 0xe1, 0x31, 0x82, 0x25, 0xe3, 0x7a,
	0xa7, 0x5c, 0xb3, 0xda, 0xad, 0x5a, 0xd5, 0x6c, 0xa3, 0x53, 0x38, 0x0f, 0xd9, 0xbd, 0x4e, 0xad,
	0x66, 0xb5, 0x2b, 0xe5, 0x06, 0xd2, 0x74, 0x02, 0x20, 0xa6, 0x14, 0x93, 0x4f, 0x1d, 0xa4, 0xdd,
	0xc7, 0x41, 0xe7, 0x20, 0xeb, 0x7b, 0x77, 0x94, 0xed, 0x09, 0x61, 0x4e, 0xc6, 0xf7, 0xee, 0x08,
	0xcb, 0xf5, 0x32, 0xe0, 0xb8, 0xae, 0x2a, 0x7b, 0x63, 0x05, 0xa6, 0xcd, 0x14, 0xd8, 0x54, 0x7e,
	0x54, 0x60, 0x72, 0xbb, 0xe5, 0x53, 0x7b, 0xf8, 0x32, 0xb5, 0x07, 0x2c, 0xec, 0x29, 0xfa, 0xef,
	0x12, 0x90, 0x27, 0x1c, 0xe3, 0x0c, 0x69, 0x9b, 0xd9, 0x2c, 0xe0, 0x91, 0x3a, 0x10, 0x2c, 0xd6,
	0xb4, 0x34, 0xb2, 0x24, 0x27, 0x71, 0xf2, 0xde, 0x75, 0x0b, 0x56, 0x03, 0xda, 0xf5, 0xdc, 0x5e,
	0x60, 0xed, 0xd3, 0x03, 0xc7, 0xed, 0x59, 0x43, 0x3b, 0x60, 0xea, 0x71, 0x26, 0x4f, 0x8a, 0x8a,
	0xb8, 0x23, 0x68, 0x75, 0x41, 0xc2, 0x17, 0x61, 0x65, 0xdf, 0x71, 0x07, 0x5e, 0xdf, 0x1a, 0x0d,
	0xec, 0x09, 0xf5, 0x03, 0x65, 0x2a, 0x4f, 0xaf, 0x34, 0xc1, 0x92, 0xd6, 0x92, 0x24, 0x19, 0xee,
	0x57, 0xe1, 0xc2, 0x5c, 0x29, 0xd6, 0x2d, 0x67, 0xc0, 0xa8, 0x4f, 0x7b, 0x96, 0x4f, 0x47, 0x03,
	0xa7, 0x6b, 0x8b, 0x76, 0x21, 0xf7, 0x57, 0xcf, 0xcc, 0x11, 0xbd, 0xa7, 0xd8, 0xc9, 0x94, 0x9b,
	0x7b, 0xbb, 0x3b, 0x1a, 0x5b, 0xe3, 0xc0, 0xee, 0xcb, 0x67, 0x37, 0x8d, 0x64, 0xba, 0xa3, 0x71,
	0x87, 0xc3, 0x18, 0x41, 0xf2, 0xf6, 0x48, 0x36, 0x18, 0x8d, 0xf0, 0xa1, 0xfe, 0x8e, 0x16, 0x5e,
	0x2e, 0x86, 0xde, 0x8b, 0x1a, 0x48, 0x58, 0x26, 0xda, 0x7b, 0x95, 0x49, 0x09, 0x16, 0x03, 0xea,
	0x1f, 0x39, 0x6e, 0x3f, 0x7c, 0xbf, 0x52, 0x20, 0x6e, 0xc3, 0x33, 0xea, 0x45, 0x9e, 0xde, 0x65,
	0xd4, 0x77, 0xed, 0xc1, 0x60, 0x62, 0xc9, 0xb3, 0x95, 0xcb, 0x68, 0xcf, 0x9a, 0xbe, 0x9d, 0xcb,
	0x26, 0xf2, 0x94, 0xe4, 0x36, 0x22, 0x66, 0x12, 0xf1, 0x9a, 0xd1, 0xab, 0xfa, 0x67, 0xa1, 0xe0,
	0xab, 0x98, 0x5a, 0x01, 0x0f, 0xaa, 0x2a, 0xcf, 0x95, 0xe8, 0x11, 0x2a, 0x16, 0x70, 0x92, 0xf7,
	0xe3, 0x20, 0xdf, 0x80, 0x17, 0x3b, 0xa3, 0x9e, 0xcd, 0xa8, 0xb4, 0xf8, 0x21, 0xed, 0x4c, 0xf1,
	0xff, 0x10, 0xa4, 0x66, 0xff, 0x43, 0x30, 0xfb, 0x9f, 0x84, 0xf4, 0xb1, 0xff, 0x24, 0xe8, 0x57,
	0x60, 0x65, 0xd6, 0x7e, 0x15, 0xeb, 0x0d, 0x48, 0x8b, 0x17, 0xb3, 0x63, 0xb7, 0xa4, 0xb1, 0x27,
	0x31, 0x22, 0x19, 0xf4, 0xdf, 0x6b, 0x50, 0x9c, 0xb3, 0x37, 0x8b, 0x36, 0x7e, 0x5a, 0xec, 0x5c,
	0xf9, 0x49, 0x48, 0x8b, 0xb7, 0x3b, 0xf5, 0xa8, 0x7c, 0xf6, 0xe4, 0xd6, 0x4e, 0xbc, 0xb3, 0x11,
	0xc9, 0xc5, 0xab, 0x53, 0x84, 0xb5, 0x2b, 0x0e, 0x96, 0xe1, 0xd2, 0x92, 0xe3, 0x38, 0x79, 0xd6,
	0x3c, 0x79, 0x52, 0x4d, 0xdd, 0xf7, 0xa4, 0x7a, 0xe1, 0x47, 0x49, 0xc8, 0xd6, 0x27, 0xed, 0xdb,
	0x83, 0xbd, 0x81, 0xdd, 0x17, 0x0f, 0x61, 0xf5, 0x96, 0x79, 0x13, 0x9d, 0xc2, 0xcb, 0x90, 0x6f,
	0x34, 0x4d, 0xab, 0xc1, 0xfb, 0xdb, 0x5e, 0xad, 0x7c, 0x15, 0x69, 0xbc, 0x01, 0xb6, 0x48, 0xd5,
	0xba, 0x66, 0xdc, 0x94, 0x98, 0x04, 0x2e, 0xc2, 0xe9, 0x4e, 0xa3, 0x7a, 0xbd, 0x63, 0x4c, 0x91,
	0x29, 0xbc, 0x0a, 0xcb, 0xf5, 0x4e, 0xcd, 0xac, 0xb6, 0x6a, 0x31, 0x74, 0x86, 0x37, 0xcb, 0x9d,
	0x5a, 0x73, 0x47, 0x82, 0x88, 0xcf, 0xdf, 0x69, 0xb4, 0xab, 0x57, 0x1b, 0xc6, 0xae, 0x44, 0xad,
	0x73, 0xd4, 0xab, 0x06, 0x69, 0xee, 0x55, 0x43, 0x91, 0x57, 0x30, 0x82, 0xdc, 0x4e, 0xb5, 0x51,
	0x26, 0x6a, 0x96, 0x7b, 0x1a, 0x2e, 0x40, 0xd6, 0x68, 0x74, 0xea, 0x0a, 0x4e, 0xe0, 0x12, 0x14,
	0xcb, 0x1d, 0xb3, 0x69, 0x55, 0x1b, 0x15, 0x62, 0xd4, 0x8d, 0x86, 0xa9, 0x28, 0x29, 0x5c, 0x84,
	0x82, 0x59, 0xad, 0x1b, 0x6d, 0xb3, 0x5c, 0x6f, 0x29, 0x24, 0xd7, 0x22, 0xd3, 0x36, 0x42, 0x1e,
	0x84, 0xd7, 0x60, 0xb5, 0xd1, 0xb4, 0x76, 0x8d, 0xbd, 0x72, 0xa7, 0x66, 0x5a, 0x37, 0xca, 0xb5,
	0x8e, 0xa1, 0x68, 0xeb, 0xf8, 0x2c, 0xe0, 0x66, 0xc3, 0xea, 0xb4, 0x76, 0xcb, 0xa6, 0x61, 0x35,
	0x9a, 0xaf, 0x28, 0xc2, 0x15, 0x5c, 0x80, 0xcc, 0x54, 0x83, 0x7b, 0xdc, 0x0b, 0xf9, 0x56, 0x99,
	0x98, 0x53, 0x63, 0xef, 0xdd, 0xe3, 0xce, 0x82, 0xab, 0xa4, 0xd9, 0x69, 0x4d, 0xd9, 0x96, 0x21,
	0xa7, 0x9c, 0xa5, 0x50, 0x29, 0x8e, 0xda, 0xa9, 0x36, 0x2a, 0x91, 0x7e, 0xf7, 0x32, 0x6b, 0x09,
	0xa4, 0x5d, 0x38, 0x84, 0x94, 0x08, 0x47, 0x06, 0x52, 0x8d, 0x66, 0xc3, 0x40, 0xa7, 0xf0, 0x69,
	0x80, 0x6a, 0xbb, 0xda, 0x30, 0x8d, 0xab, 0xa4, 0x5c, 0xe3, 0x66, 0x0b, 0x44, 0xe8, 0x40, 0x6e,
	0xed, 0x12, 0x2c, 0x56, 0xdb, 0x7b, 0xb5, 0x66, 0xd9, 0x54, 0x66, 0x56, 0xdb, 0xd7, 0x3b, 0x4d,
	0x93, 0x13, 0x11, 0xce, 0xc1, 0x42, 0xb5, 0x6d, 0x1a, 0x5f, 0x36, 0xb9, 0x5d, 0x82, 0x26, 0xbd,
	0x8a, 0xee, 0x5d, 0xb9, 0xf0, 0x46, 0x12, 0x52, 0xe6, 0x64, 0x44, 0x79, 0x80, 0x44, 0xb4, 0xcd,
	0x9b, 0x2d, 0x2e, 0x32, 0x0b, 0xa9, 0x6a, 0xc3, 0x7c, 0x11, 0x7d, 0x25, 0x81, 0x01, 0xd2, 0x1d,
	0x31, 0xfe, 0xea, 0x02, 0x1f, 0x57, 0x1b, 0xe6, 0x0b, 0x97, 0xd1, 0xeb, 0x09, 0x3e, 0x6d, 0x47,
	0x02, 0x5f, 0x0b, 0x09, 0x5b, 0xdb, 0xe8, 0xeb, 0x11, 0x61, 0x6b, 0x1b, 0x7d, 0x23, 0x24, 0x5c,
	0xda, 0x42, 0xdf, 0x8c, 0x08, 0x97, 0xb6, 0xd0, 0xb7, 0x42, 0xc2, 0xe5, 0x6d, 0xf4, 0x46, 0x44,
	0xb8, 0xbc, 0x8d, 0xbe, 0xbd, 0xc0, 0x6d, 0x11, 0x96, 0x5c, 0xda, 0x42, 0xdf, 0xc9, 0x44, 0xd0,
	0xe5, 0x6d, 0xf4, 0xdd, 0x0c, 0x8f, 0x7f, 0x14, 0x55, 0xf4, 0x3d, 0xc4, 0xd5, 0xe4, 0x01, 0x42,
	0xdf, 0x17, 0x43, 0x4e, 0x42, 0x3f, 0x40, 0xdc, 0x46, 0x8e, 0x15, 0xe0, 0x9b, 0x82, 0x72, 0xd3,
	0x28, 0x13, 0xf4, 0xc3, 0x05, 0x9c, 0x83, 0xc5, 0x5d, 0xa3, 0x52, 0xad, 0x97, 0x6b, 0x08, 0x8b,
	0x2f, 0xb8, 0x57, 0x7e, 0x7c, 0x91, 0x0f, 0x79, 0x7a, 0xa2, 0x9f, 0xb4, 0xb8, 0xc0, 0x1b, 0x65,
	0x52, 0x79, 0xb9, 0x4c, 0xd0, 0x4f, 0x2f, 0x72, 0x81, 0x37, 0xca, 0x44, 0xf9, 0xeb, 0x67, 0x2d,
	0xce, 0x28, 0x48, 0x6f, 0x5d, 0xe4, 0x4a, 0x2b, 0xfc, 0xcf, 0x5b, 0x38, 0x03, 0xc9, 0x9d, 0xaa,
	0x89, 0x7e, 0x21, 0xa4, 0xf1, 0x14, 0x45, 0xbf, 0x44, 0x1c, 0xd9, 0x36, 0x4c, 0xf4, 0x2b, 0x8e,
	0x4c, 0x9b, 0x9d, 0x56, 0xcd, 0x40, 0x8f, 0x73, 0xe5, 0xae, 0x1a, 0xcd, 0xba, 0x61, 0x92, 0x9b,
	0xe8, 0xd7, 0x82, 0xfd, 0x4b, 0xed, 0x66, 0x03, 0xbd, 0x8d, 0x2e, 0xec, 0x01, 0x3a, 0x5e, 0xfe,
	0x5c, 0xe1, 0x4e, 0xe3, 0x5a, 0xa3, 0xf9, 0x4a, 0x03, 0x9d, 0xe2, 0x40, 0x8b, 0x18, 0xad, 0x32,
	0x31, 0x90, 0x86, 0x01, 0x16, 0x2a, 0xcd, 0x7a, 0xbd, 0x6a, 0xa2, 0x04, 0x5e, 0x82, 0x0c, 0x69,
	0xd6, 0x6a, 0x3b, 0xe5, 0xca, 0x35, 0x94, 0xdc, 0x59, 0x83, 0x52, 0xd7, 0x1b, 0x6e, 0x4e, 0xbc,
	0x31, 0x1b, 0xef, 0xd3, 0xcd, 0x23, 0x87, 0xd1, 0x20, 0x90, 0xff, 0x22, 0xdb, 0x5f, 0x10, 0x3f,
	0x97, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf9, 0x02, 0xd7, 0x9d, 0x7f, 0x26, 0x00, 0x00,
}
