#!/bin/bash

# Runs any hooks in mic/git/hooks, and exits if any of them fail.
set -e

# This is necessary because the Emacs extensions don't set GIT_DIR.
if [ -z "$GIT_DIR" ]; then
  DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
  GIT_DIR="${DIR}/.."
fi

MISC_DIR="$GIT_DIR/../misc"
if [ -d "$MISC_DIR" ]; then
  for hook in $MISC_DIR/git/hooks/*; do
    $hook
  done
fi
